### ISSUE TITLE
Can't display items correctly in Laravel.

### ISSUE THREAD

**Issue by sammymwangangi** [twoquethree/laravel-uikit#31]
I am having issues with displaying items such as images in Laravel.
This is my code:

![uikit-laravel-grid](https://user-images.githubusercontent.com/17009772/41695979-4c4d1c26-751a-11e8-9146-19e4797af49c.PNG)

And this is how it displays:

![display](https://user-images.githubusercontent.com/17009772/41696006-77905ccc-751a-11e8-850a-951db78221ce.PNG)

I want them to display in four columns...even when i use columns it's the same case.
Kindly help me.

**Comment by cesaramirez** [comment]
This issue is not related with package but you can use `asset`helper

``` html
<img class="img-responsive" src="{{ asset(`products/'.$product->image) }}"
```

You must also take into account where you have stored the images to make a correct reference to the image.

**Comment by sammymwangangi** [comment]
Thanks for your response...

**Comment by mattfletcher** [comment]
You need to move that uk-child-width class onto a div outside the foreach

Or, change it to a uk-width and add a uk-grid attribute outside the foreach

**Comment by sammymwangangi** [comment]
@mattfletcher Thanks,will try that.
